name: Java CI with Maven

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master, dev, "release-**"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["11"]
        # java: ["11", "16", "17"]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: LukeWinikates/java-lib
          ref: syslog
          path: java-lib
      - uses: actions/checkout@v3
        with:
          path: wavefront-proxy
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
          cache: maven
      - name: install java-lib
        run: cd java-lib; mvn clean install -DskipTests
      - name: Check code format
        run: cd wavefront-proxy; mvn -f proxy git-code-format:validate-code-format
      - name: Build with Maven
        run: cd wavefront-proxy; mvn -f proxy test -B
